# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"7\n\x08Transfer\x12\x1c\n\x05ttype\x18\x01 \x01(\x0e\x32\r.TransferType\x12\r\n\x05tdata\x18\x02 \x01(\x0c\"\x16\n\x07Message\x12\x0b\n\x03mes\x18\x01 \x01(\x0c\"%\n\nCipherText\x12\x0b\n\x03rkc\x18\x01 \x01(\x0c\x12\n\n\x02\x65\x63\x18\x02 \x01(\x0c\"X\n\x08\x43hamHash\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x0e\n\x06random\x18\x02 \x01(\x0c\x12\x17\n\x02\x63t\x18\x03 \x01(\x0b\x32\x0b.CipherText\x12\n\n\x02N1\x18\x04 \x01(\x0c\x12\t\n\x01\x65\x18\x05 \x01(\x0c\"6\n\x08\x43heckSet\x12\x13\n\x01m\x18\x01 \x01(\x0b\x32\x08.Message\x12\x15\n\x02\x63h\x18\x02 \x01(\x0b\x32\t.ChamHash\"M\n\x08\x41\x64\x61ptSet\x12\x14\n\x02m1\x18\x01 \x01(\x0b\x32\x08.Message\x12\x14\n\x02m2\x18\x02 \x01(\x0b\x32\x08.Message\x12\x15\n\x02\x63h\x18\x03 \x01(\x0b\x32\t.ChamHash\"\x1b\n\nCheckState\x12\r\n\x05\x63heck\x18\x01 \x01(\x08*Z\n\x0cTransferType\x12\x08\n\x04Hash\x10\x00\x12\t\n\x05\x43heck\x10\x01\x12\t\n\x05\x41\x64\x61pt\x10\x02\x12\x0c\n\x08HashRecv\x10\x03\x12\r\n\tCheckRecv\x10\x04\x12\r\n\tAdaptRecv\x10\x05\x62\x06proto3'
)

_TRANSFERTYPE = _descriptor.EnumDescriptor(
  name='TransferType',
  full_name='TransferType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Hash', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Check', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Adapt', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HashRecv', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CheckRecv', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AdaptRecv', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=388,
  serialized_end=478,
)
_sym_db.RegisterEnumDescriptor(_TRANSFERTYPE)

TransferType = enum_type_wrapper.EnumTypeWrapper(_TRANSFERTYPE)
Hash = 0
Check = 1
Adapt = 2
HashRecv = 3
CheckRecv = 4
AdaptRecv = 5



_TRANSFER = _descriptor.Descriptor(
  name='Transfer',
  full_name='Transfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ttype', full_name='Transfer.ttype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tdata', full_name='Transfer.tdata', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=69,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mes', full_name='Message.mes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=93,
)


_CIPHERTEXT = _descriptor.Descriptor(
  name='CipherText',
  full_name='CipherText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rkc', full_name='CipherText.rkc', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ec', full_name='CipherText.ec', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=132,
)


_CHAMHASH = _descriptor.Descriptor(
  name='ChamHash',
  full_name='ChamHash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='ChamHash.hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='random', full_name='ChamHash.random', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ct', full_name='ChamHash.ct', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='N1', full_name='ChamHash.N1', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='ChamHash.e', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=222,
)


_CHECKSET = _descriptor.Descriptor(
  name='CheckSet',
  full_name='CheckSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='CheckSet.m', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ch', full_name='CheckSet.ch', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=278,
)


_ADAPTSET = _descriptor.Descriptor(
  name='AdaptSet',
  full_name='AdaptSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='m1', full_name='AdaptSet.m1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m2', full_name='AdaptSet.m2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ch', full_name='AdaptSet.ch', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=357,
)


_CHECKSTATE = _descriptor.Descriptor(
  name='CheckState',
  full_name='CheckState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='check', full_name='CheckState.check', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=386,
)

_TRANSFER.fields_by_name['ttype'].enum_type = _TRANSFERTYPE
_CHAMHASH.fields_by_name['ct'].message_type = _CIPHERTEXT
_CHECKSET.fields_by_name['m'].message_type = _MESSAGE
_CHECKSET.fields_by_name['ch'].message_type = _CHAMHASH
_ADAPTSET.fields_by_name['m1'].message_type = _MESSAGE
_ADAPTSET.fields_by_name['m2'].message_type = _MESSAGE
_ADAPTSET.fields_by_name['ch'].message_type = _CHAMHASH
DESCRIPTOR.message_types_by_name['Transfer'] = _TRANSFER
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['CipherText'] = _CIPHERTEXT
DESCRIPTOR.message_types_by_name['ChamHash'] = _CHAMHASH
DESCRIPTOR.message_types_by_name['CheckSet'] = _CHECKSET
DESCRIPTOR.message_types_by_name['AdaptSet'] = _ADAPTSET
DESCRIPTOR.message_types_by_name['CheckState'] = _CHECKSTATE
DESCRIPTOR.enum_types_by_name['TransferType'] = _TRANSFERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transfer = _reflection.GeneratedProtocolMessageType('Transfer', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFER,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:Transfer)
  })
_sym_db.RegisterMessage(Transfer)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

CipherText = _reflection.GeneratedProtocolMessageType('CipherText', (_message.Message,), {
  'DESCRIPTOR' : _CIPHERTEXT,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:CipherText)
  })
_sym_db.RegisterMessage(CipherText)

ChamHash = _reflection.GeneratedProtocolMessageType('ChamHash', (_message.Message,), {
  'DESCRIPTOR' : _CHAMHASH,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ChamHash)
  })
_sym_db.RegisterMessage(ChamHash)

CheckSet = _reflection.GeneratedProtocolMessageType('CheckSet', (_message.Message,), {
  'DESCRIPTOR' : _CHECKSET,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:CheckSet)
  })
_sym_db.RegisterMessage(CheckSet)

AdaptSet = _reflection.GeneratedProtocolMessageType('AdaptSet', (_message.Message,), {
  'DESCRIPTOR' : _ADAPTSET,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:AdaptSet)
  })
_sym_db.RegisterMessage(AdaptSet)

CheckState = _reflection.GeneratedProtocolMessageType('CheckState', (_message.Message,), {
  'DESCRIPTOR' : _CHECKSTATE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:CheckState)
  })
_sym_db.RegisterMessage(CheckState)


# @@protoc_insertion_point(module_scope)
